#include <iostream>
#include <limits>
int main(int, char **) {
  std::cout<<"char               "
    << static_cast< int >(std::numeric_limits< char >::min()) << "\t"
    << static_cast< int >(std::numeric_limits< char >::max()) << "\n\n"
    <<"unsigned char      "
    << static_cast< int >(std::numeric_limits< unsigned char >::min()) << "\t"
    << static_cast< int >(std::numeric_limits< unsigned char >::max()) << "\n\n"
    <<"short          "
    << std::numeric_limits< short >::min() << "\t"
    << std::numeric_limits< short >::max() << "\t(approx  32x10^3)\n\n"
    <<"unsigned short    "
    << std::numeric_limits< unsigned short >::min() << "\t"
    << std::numeric_limits< unsigned short >::max() << "\t(approx  65x10^3)\n\n"
    <<"int        "
    << std::numeric_limits< int >::min() << "\t"
    << std::numeric_limits< int >::max() << "\t(approx  21x10^8)\n\n"
    <<"unsigned int    "
    << std::numeric_limits< unsigned int >::min() << "\t"
    << std::numeric_limits< unsigned int >::max() << "\t(approx  42x10^8)\n\n"
    <<"long    "
    << std::numeric_limits< long >::min() << "\t"
    << std::numeric_limits< long >::max() << "\t(approx  21x10^8)\n\n"
    <<"unsigned long    "
    << std::numeric_limits< unsigned long >::min() << "\t"
    << std::numeric_limits< unsigned long >::max() << "\t(approx  42x10^8)\n\n"
    <<"long long  "
    << std::numeric_limits< long long >::min() << "\t  "
    << std::numeric_limits< long long >::max() << "\t(approx  92x10^17)\n\n"
    <<"unsigned long long    "
    << std::numeric_limits< unsigned long long >::min() << "\t  "
    << std::numeric_limits< unsigned long long >::max() << "\t(approx  18x10^18)\n";
}
